config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope controller: :sessions do
    get :login, action: :new, as: :new_login
    post :login, action: :login, as: :login
    delete :logout, action: :logout, as: :logout
  end

  get 'searches/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  root to: 'articles#index'

  resources :articles, only: :index do
    get :search, on: :collection
  end

  resources :searches, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
end

app/models/search.rb
# frozen_string_literal: true

class Search < ApplicationRecord
  scope :of_user, ->(user) { where(user: user) }

  belongs_to :user
  enum status: %i[incomplete complete]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  enum role: %i[guest admin]

  has_many :searches

  validates :username, :password, presence: true, if: :admin?
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  helper_method :current_user
  attr_reader :current_user

  before_action :set_user

  private

  def set_user
    if cookies[:user_id].blank?
      @current_user = User.create(role: :guest)
      cookies[:user_id] = @current_user.id
    else
      @current_user = User.find_by(id: cookies[:user_id])
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index; end

  def search
    @articles = if params[:query].present?
                  articles_finder.save_search(params[:query])
                  articles_finder.search(params[:query])
                else
                  []
                end
    render :index
  end

  private

  def articles_finder
    @articles_finder ||= Finders::Articles.new(current_user)
  end
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  def index
    authorize Search

    @searches = policy_scope(Search).complete.select(:query).distinct
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :set_user

  def new
    @user = User.new
  end

  def login
    user = User.find_by(username: user_params[:username], password: user_params[:password])

    if user.present?
      cookies[:prev_user_id] = cookies[:user_id]
      cookies[:user_id] = user.id
      @current_user = user
      redirect_to root_path
    else
      flash[:alert] = 'Wrong username or password'

      render :new, status: :unprocessable_entity
    end
  end

  def logout
    cookies[:user_id] = (cookies[:prev_user_id] if prev_user&.guest?)

    redirect_to root_path
  end

  private

  def prev_user
    @prev_user ||= cookies[:prev_user_id] && User.find_by(id: cookies[:prev_user_id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def logged_in?
    current_user&.admin?
  end

  def current_page?(controller, action)
    params[:controller] == controller && params[:action] == action
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<%= turbo_frame_tag(dom_id(article)) do %>
  <div class="article pl-0 p-2 text-lg text-gray-600">
    <div class="p-3">
      <%= article.title %>
    </div>

    <hr class='ml-3 w-1/5 border-b border-gray-300'>
  </div>
<% end %>

app/views/articles/index.html.erb
<%= turbo_frame_tag("articles", class: 'w-full') do %>
  <div id="articles w-full">
    <% if @articles.present? %>
      <h1 class='text-2xl m-3 mb-5 pl-0 p-3 border-b border-gray-500 w-1/4'>
        Results for <%= params[:query].inspect %>
      </h1>
      <%= render @articles %>
    <% else %>
      <div class="text-gray-600 text-lg">
        <% if params[:query].present? %>
          No results for this search "<%= params[:query] %>"
        <% else %>
          You can search for articles from the box at the top..
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpjuiceTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body class='h-full'>
    <nav class='bg-gray-800 flex justify-center shadow-lg w-full'>
      <div class='h-16 flex w-1/2 items-center justify-between'>
        <div id='search-form' data-controller='search' class='w-1/2'>
          <%= form_with url: search_articles_path, method: :get, data: { local: current_page?('articles', 'index'), 'search-target': 'form', 'turbo-frame': 'articles' } do |form| %>
            <div class="relative w-full text-gray-500 focus-within:text-gray-200">
              <span class="absolute inset-y-0 left-0 flex items-center pl-2 mr-2">
                <button type="submit" class="p-1 focus:outline-none focus:shadow-outline">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                </button>
              </span>
              <%= form.search_field :query, autofocus: params[:query].present?, onfocus: "var v = this.value; this.value = ''; this.value = v",
                value: params[:query], id: :query, class: "pl-10 py-2 w-full text-sm bg-transparent border-none focus:bg-gray-500 focus:ring-0", placeholder: 'Search articles',
                data: { 'action': 'keyup->search#search' } %>
            </div>
          <% end %>
        </div>
        <div class="links flex text-white">
          <div class="mr-2 p-2 rounded hover:text-gray-200 hover:bg-gray-500">
            <%= link_to 'Searches', searches_path %>
          </div>

          <div class="flex bg-gray-500 hover:bg-gray-600 hover:text-gray-200 rounded">
            <% if logged_in? %>
              <%= link_to logout_path, method: :delete, class: 'hover:text-gray-200' do %>
                <div class="flex items-center p-2">
                  <b>Admin</b>
                  <%= heroicon 'logout', variant: :outline, options: { class: "ml-2 w-6" } %>
                </div>
              <% end %>
            <% else %>
              <%= link_to login_path do %>
                <div class="flex items-center p-2">
                  <span>Login</span>
                  <%= heroicon 'login', variant: :outline, options: { class: "ml-2 w-6" } %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <main class="container w-1/2 mx-auto mt-20 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/searches/index.html.erb
<div class="flex flex-col w-full">
  <h1 class='text-2xl m-3 mb-5 pl-0 p-3 border-b border-gray-500 w-1/5'>
    <%= current_user.admin? ? 'All' : 'My' %>
    Searches
  </h1>

  <div id="searches" class="m-3 mb-5 pl-0 p-3 w-full">
    <% if @searches.present? %>
      <% @searches.each do |search| %>
        <div class="search mb-3 pl-0 p-2 text-lg text-gray-600">
          <span class="block mb-2 ">
            <%= search.query %>
          </span>
          <hr class='ml-0 m-1 w-1/5 border-b border-gray-300'>
        </div>
      <% end %>
    <% else %>
      <div>No searches yet</div>
    <% end %>
  </div>
</div>